// Cross-implementation E2EE vector tests.
//
// test/vectors/e2ee_vectors.json is generated by the Go side
// (olace-e2ee-go/cmd/genvectors) and enforced verbatim by BOTH
// implementations. A failure here means the Dart client and the Go daemon
// no longer agree on wire bytes: that is a protocol break, never a
// refactor. Fix the code, never the vectors.

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:olace_crypto/olace_crypto.dart';
import 'package:test/test.dart';

Uint8List hexDecode(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String hexEncode(List<int> bytes) =>
    bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();

void main() {
  final vectors = jsonDecode(
    File('test/vectors/e2ee_vectors.json').readAsStringSync(),
  ) as Map<String, dynamic>;

  final x = vectors['x25519'] as Map<String, dynamic>;
  final fields = vectors['fields'] as Map<String, dynamic>;
  final transcripts = vectors['transcripts'] as Map<String, dynamic>;
  final derivedKeys = vectors['derived_keys'] as Map<String, dynamic>;

  String fStr(String k) => fields[k] as String;
  int fInt(String k) => fields[k] as int;

  P2PLocalIdentity aliceMobile() => P2PLocalIdentity(
        deviceId: fStr('mobile_device_id'),
        publicKey: base64Encode(hexDecode(x['alice_public_hex'] as String)),
        privateKey: base64Encode(hexDecode(x['alice_scalar_hex'] as String)),
        fingerprint: '',
        keyVersion: fInt('mobile_key_version'),
        createdAt: 0,
      );

  P2PPeerIdentity bobDesktop() => P2PPeerIdentity(
        deviceId: fStr('desktop_device_id'),
        publicKey: base64Encode(hexDecode(x['bob_public_hex'] as String)),
        fingerprint: '',
        keyVersion: fInt('desktop_key_version'),
      );

  SimpleKeyPairData ephA() => SimpleKeyPairData(
        hexDecode(x['eph_a_scalar_hex'] as String),
        publicKey: SimplePublicKey(
          hexDecode(x['eph_a_public_hex'] as String),
          type: KeyPairType.x25519,
        ),
        type: KeyPairType.x25519,
      );

  SimplePublicKey ephBPub() => SimplePublicKey(
        hexDecode(x['eph_b_public_hex'] as String),
        type: KeyPairType.x25519,
      );

  test('X25519 matches RFC 7748 known answers', () async {
    final x25519 = X25519();
    final alice = SimpleKeyPairData(
      hexDecode(x['alice_scalar_hex'] as String),
      publicKey: SimplePublicKey(
        hexDecode(x['alice_public_hex'] as String),
        type: KeyPairType.x25519,
      ),
      type: KeyPairType.x25519,
    );
    final shared = await x25519.sharedSecretKey(
      keyPair: alice,
      remotePublicKey: SimplePublicKey(
        hexDecode(x['bob_public_hex'] as String),
        type: KeyPairType.x25519,
      ),
    );
    expect(
      hexEncode(await shared.extractBytes()),
      x['shared_alice_bob_hex'],
    );
  });

  test('transcripts match', () {
    expect(
      P2PCrypto.buildHelloTranscript(
        ticket: fStr('ticket'),
        pairId: fStr('pair_id'),
        userId: fStr('user_id'),
        mobileDeviceId: fStr('mobile_device_id'),
        desktopDeviceId: fStr('desktop_device_id'),
        mobileKeyVersion: fInt('mobile_key_version'),
        desktopKeyVersion: fInt('desktop_key_version'),
        sessionId: fStr('session_id'),
        clientEphemeralPublicKey: fStr('client_eph_pub_b64'),
        clientNonce: fStr('client_nonce'),
      ),
      (transcripts['p2p_hello'] as Map)['transcript'],
    );
    expect(
      P2PCrypto.buildAckTranscript(
        ticket: fStr('ticket'),
        pairId: fStr('pair_id'),
        userId: fStr('user_id'),
        mobileDeviceId: fStr('mobile_device_id'),
        desktopDeviceId: fStr('desktop_device_id'),
        mobileKeyVersion: fInt('mobile_key_version'),
        desktopKeyVersion: fInt('desktop_key_version'),
        sessionId: fStr('session_id'),
        clientEphemeralPublicKey: fStr('client_eph_pub_b64'),
        serverEphemeralPublicKey: fStr('server_eph_pub_b64'),
        clientNonce: fStr('client_nonce'),
        serverNonce: fStr('server_nonce'),
      ),
      (transcripts['p2p_ack'] as Map)['transcript'],
    );
    expect(
      P2PCrypto.buildSessionInfo(
        ticket: fStr('ticket'),
        pairId: fStr('pair_id'),
        userId: fStr('user_id'),
        mobileDeviceId: fStr('mobile_device_id'),
        desktopDeviceId: fStr('desktop_device_id'),
        mobileKeyVersion: fInt('mobile_key_version'),
        desktopKeyVersion: fInt('desktop_key_version'),
        sessionId: fStr('session_id'),
        clientEphemeralPublicKey: fStr('client_eph_pub_b64'),
        serverEphemeralPublicKey: fStr('server_eph_pub_b64'),
        clientNonce: fStr('client_nonce'),
        serverNonce: fStr('server_nonce'),
      ),
      transcripts['p2p_session_info'],
    );
    expect(
      P2PCrypto.buildSecureRelayHelloTranscript(
        pairId: fStr('pair_id'),
        userId: fStr('user_id'),
        mobileDeviceId: fStr('mobile_device_id'),
        desktopDeviceId: fStr('desktop_device_id'),
        mobileKeyVersion: fInt('mobile_key_version'),
        desktopKeyVersion: fInt('desktop_key_version'),
        sessionId: fStr('session_id'),
        desktopEphemeralPublicKey: fStr('server_eph_pub_b64'),
        desktopNonce: fStr('server_nonce'),
      ),
      (transcripts['relay_hello'] as Map)['transcript'],
    );
    expect(
      P2PCrypto.buildSecureRelayAckTranscript(
        pairId: fStr('pair_id'),
        userId: fStr('user_id'),
        mobileDeviceId: fStr('mobile_device_id'),
        desktopDeviceId: fStr('desktop_device_id'),
        mobileKeyVersion: fInt('mobile_key_version'),
        desktopKeyVersion: fInt('desktop_key_version'),
        sessionId: fStr('session_id'),
        desktopEphemeralPublicKey: fStr('server_eph_pub_b64'),
        mobileEphemeralPublicKey: fStr('client_eph_pub_b64'),
        desktopNonce: fStr('server_nonce'),
        mobileNonce: fStr('client_nonce'),
      ),
      (transcripts['relay_ack'] as Map)['transcript'],
    );
    expect(
      P2PCrypto.buildSecureRelayForwardSecretSessionInfo(
        pairId: fStr('pair_id'),
        userId: fStr('user_id'),
        mobileDeviceId: fStr('mobile_device_id'),
        desktopDeviceId: fStr('desktop_device_id'),
        mobileKeyVersion: fInt('mobile_key_version'),
        desktopKeyVersion: fInt('desktop_key_version'),
        sessionId: fStr('session_id'),
        desktopEphemeralPublicKey: fStr('server_eph_pub_b64'),
        mobileEphemeralPublicKey: fStr('client_eph_pub_b64'),
        desktopNonce: fStr('server_nonce'),
        mobileNonce: fStr('client_nonce'),
      ),
      transcripts['relay_fs_info'],
    );
  });

  test('transcript HMAC signatures match and verify', () async {
    for (final name in ['p2p_hello', 'p2p_ack', 'relay_hello', 'relay_ack']) {
      final tv = transcripts[name] as Map;
      final sig = await P2PCrypto.signHelloOrAck(
        localIdentity: aliceMobile(),
        peerIdentity: bobDesktop(),
        transcript: tv['transcript'] as String,
      );
      expect(sig, tv['hmac_b64'], reason: name);
      expect(
        await P2PCrypto.verifyHelloOrAck(
          localIdentity: aliceMobile(),
          peerIdentity: bobDesktop(),
          transcript: tv['transcript'] as String,
          signature: sig,
        ),
        isTrue,
        reason: name,
      );
    }
  });

  test('P2P session key derivation matches', () async {
    final ctx = await P2PCrypto.deriveSessionContext(
      sessionId: fStr('session_id'),
      localIdentity: aliceMobile(),
      peerIdentity: bobDesktop(),
      localEphemeralKeyPair: ephA(),
      remoteEphemeralPublicKey: ephBPub(),
      info: transcripts['p2p_session_info'] as String,
    );
    expect(
      hexEncode(await ctx.sessionKey.extractBytes()),
      derivedKeys['p2p_session_key_hex'],
    );
  });

  test('forward-secret relay key derivation matches', () async {
    final ctx = await P2PCrypto.deriveForwardSecretSessionContext(
      sessionId: fStr('session_id'),
      localKeyVersion: fInt('mobile_key_version'),
      localEphemeralKeyPair: ephA(),
      remoteEphemeralPublicKey: ephBPub(),
      info: transcripts['relay_fs_info'] as String,
    );
    expect(
      hexEncode(await ctx.sessionKey.extractBytes()),
      derivedKeys['relay_fs_key_hex'],
    );
  });

  test('fingerprint matches', () async {
    final fp = vectors['fingerprint'] as Map<String, dynamic>;
    expect(
      await P2PCrypto.fingerprintForPublicKey(fp['public_key_b64'] as String),
      fp['fingerprint_hex'],
    );
  });

  test('envelope decrypt vectors accepted, replays rejected', () async {
    for (final ev in vectors['envelopes'] as List) {
      final e = ev as Map<String, dynamic>;
      final ctx = P2PCryptoContext(
        sessionId: fStr('session_id'),
        sessionKey: SecretKey(hexDecode(e['session_key_hex'] as String)),
        localKeyVersion: 1,
      );
      final envelope = (e['envelope'] as Map).cast<String, dynamic>();
      final got = await ctx.decrypt(envelope);
      expect(got, isNotNull, reason: '${e['name']}: decrypt failed');
      expect(got, jsonDecode(e['plaintext_json'] as String),
          reason: e['name'] as String);
      expect(await ctx.decrypt(envelope), isNull,
          reason: '${e['name']}: replayed envelope accepted');
    }
  });

  test('envelope round trip: encrypt then decrypt across contexts', () async {
    final key = hexDecode(derivedKeys['p2p_session_key_hex'] as String);
    final sender = P2PCryptoContext(
      sessionId: fStr('session_id'),
      sessionKey: SecretKey(key),
      localKeyVersion: fInt('mobile_key_version'),
    );
    final receiver = P2PCryptoContext(
      sessionId: fStr('session_id'),
      sessionKey: SecretKey(key),
      localKeyVersion: fInt('desktop_key_version'),
    );
    final payload = {'type': 'chat_request', 'prompt': 'round trip'};
    final envelope = await sender.encrypt(payload);
    expect(await receiver.decrypt(envelope), payload);
  });
}
